#version 450



layout(local_size_x = FFT_N) in;

// binding = 0 debe coincidir con el índice en tu vector de images/uniformObjects
layout(binding = 0, rgba32f) uniform image2D fftDataIn;
layout(binding = 1, rgba32f) uniform image2D fftDataOut;
layout(binding = 2, rgba32f) uniform image2D fftDerivatesTemp;

layout(std140,push_constant)uniform  Push {
    int stage;
} push;



const float PI = 3.14159265358979323846;
vec2 complexExp(float angle)
{
    return vec2(cos(angle), sin(angle));
}

vec2 complexMul(vec2 a, vec2 b)
{
    return vec2(a.x * b.x - a.y * b.y,
            a.x * b.y + a.y * b.x);
}
uint bitReverse(uint x, uint log2n)
{
    uint n = 0u;
    for (uint i = 0u; i < log2n; ++i) {
        n <<= 1u;
        n |= (x & 1u);
        x >>= 1u;
    }
    return n;
}

shared vec2 A[FFT_N];
vec2 calculateK(uint fila, uint column){

    int iiCol = (column <= FFT_N/2) ? int(column) : int(column - FFT_N);
    int iiFil = (fila    <= FFT_N/2) ? int(fila)    : int(fila    - FFT_N);


    return vec2(iiCol, iiFil); // AHORA sí, esto es tu vector de frecuencia 2D
}

void main() {
    if (push.stage == 0){
        uint fila = gl_WorkGroupID.x;
        uint column = gl_LocalInvocationID.x; //Numero de invocacion, las que comparten memoria
        uint log2n = uint(log2(float(FFT_N)));

        uint rev = bitReverse(column, log2n);
        vec2 valueIn = imageLoad(fftDataIn, ivec2(rev, fila)).xy;
        if (gl_WorkGroupID.y == 1){
           vec2 k = calculateK(rev,fila);
        valueIn = complexMul(valueIn,vec2(0,k.x));
        } else if (gl_WorkGroupID.y == 2){
            vec2 k = calculateK(rev,fila);
            valueIn = complexMul(valueIn,vec2(0,k.y));
        }
        A[column] = valueIn ; //Cada hilo carga su columna
        barrier(); //Esperar a que la fila  se quede lista

        uint h = FFT_N >> 1u; //Emprezar la IFFT en la FILA (la columna es la que varia)
        for (uint s = 1u; s <= log2n; ++s)
        {
            uint m = 1u << s;
            uint m2 = m >> 1u;
            float angle = 2.0 * PI / float(m);

            if (column < h) {
                uint j = column % m2;
                uint blockIdx = column / m2;
                uint k = blockIdx * m + j;

                vec2 w = complexExp(angle * float(j));
                vec2 t = complexMul(w, A[k + m2]);
                vec2 u = A[k];
                A[k] = u + t;
                A[k + m2] = u - t;
            }
            barrier();
        }
        //Escribir
        if (gl_WorkGroupID.y == 0){
            vec4 initialValue = imageLoad(fftDataIn,ivec2(column,fila));
            imageStore(fftDataIn, ivec2(column, fila), vec4(initialValue.xy,A[column]));
        } else if (gl_WorkGroupID.y== 1) {
            vec4 initialValue = imageLoad(fftDerivatesTemp,ivec2(column,fila));
            imageStore(fftDerivatesTemp, ivec2(column, fila), vec4(A[column],initialValue.zw));
        } else {
            vec4 initialValue = imageLoad(fftDerivatesTemp,ivec2(column,fila));
            imageStore(fftDerivatesTemp, ivec2(column, fila), vec4(initialValue.xy,A[column]));
        }

    } else {
        uint column = gl_WorkGroupID.x;
        uint fila = gl_LocalInvocationID.x; //Numero de invocacion, las que comparten memoria
        uint log2n = uint(log2(float(FFT_N)));

        uint rev = bitReverse(fila, log2n);
        vec2 valueIn;
        if (gl_WorkGroupID.y == 0){
            valueIn = imageLoad(fftDataIn, ivec2(column,rev)).zw;
        } else if (gl_WorkGroupID.y== 1) {
            valueIn = imageLoad(fftDerivatesTemp, ivec2(column,rev)).xy;
        } else {
            valueIn = imageLoad(fftDerivatesTemp, ivec2(column,rev)).zw;
        }
        A[fila] = valueIn; //Cada hilo carga su columna
        barrier(); //Esperar a que la fila  se quede lista

        uint h = FFT_N >> 1u; //Emprezar la IFFT en la FILA (la columna es la que varia)
        for (uint s = 1u; s <= log2n; ++s)
        {
            uint m = 1u << s;
            uint m2 = m >> 1u;
            float angle = 2.0 * PI / float(m);

            if (fila < h) {
                uint j = fila % m2;
                uint blockIdx = fila / m2;
                uint k = blockIdx * m + j;

                vec2 w = complexExp(angle * float(j));
                vec2 t = complexMul(w, A[k + m2]);
                vec2 u = A[k];
                A[k] = u + t;
                A[k + m2] = u - t;
            }
            barrier();
        }
        vec4 initialValue = imageLoad(fftDataOut,ivec2(column,fila));

        if (gl_WorkGroupID.y == 0){
            imageStore(fftDataOut, ivec2(column, fila), vec4(A[fila].x,initialValue.yzw));
        } else if (gl_WorkGroupID.y== 1) {
            imageStore(fftDataOut, ivec2(column, fila), vec4(initialValue.x,A[fila].x,initialValue.zw));
        } else {
            imageStore(fftDataOut, ivec2(column, fila), vec4(initialValue.xy,A[fila].x,initialValue.w));
        }
    }
}