#version 450
#include "../glsl/fftGeral.glsl"
layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 1, rg32f) uniform readonly image2D h0Data; // .xy = h0(k), .zw = conj(h0(-k))
layout(binding = 0, rgba32f) uniform image2D fftDataIn;       // h(k,t) -> entrada del ifft.comp

layout(std140, push_constant) uniform Push {
    float time;
} push;
const float G  = 9.81;

void main() {
    ivec2 idx = ivec2(gl_GlobalInvocationID.xy);
    ivec2 idy = ivec2(
            (int(FFT_N) - idx.x) % int(FFT_N),
            (int(FFT_N) - idx.y) % int(FFT_N)
    );

    vec2 k = calculateK(idx.y, idx.x);
    float kLen = length(k);

    vec2 h0 = imageLoad(h0Data, idx).xy;
    vec2 h1 = imageLoad(h0Data, idy).xy;

    float omega = sqrt(G * kLen);
    float phase = omega * push.time;

    vec2 h = complexMul(
            h0,
            complexExp(phase)
    ) + complexMul(
            vec2(h1.x, -h1.y),
            complexExp(-phase)
    );
    imageStore(fftDataIn, idx, vec4(h, 0.0, 0.0));
}